site_name: Pipeflow
site_description: A type-safe, async-first data processing pipeline framework
site_author: ZByteAlchemy
repo_url: https://github.com/zbytealchemy/pipeflow
repo_name: zbytealchemy/pipeflow

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Basic Concepts: getting-started/concepts.md
  - User Guide:
    - Pipes: user-guide/pipes.md
    - Pipelines: user-guide/pipelines.md
    - Configuration: user-guide/configuration.md
    - Error Handling: user-guide/error-handling.md
    - Monitoring: user-guide/monitoring.md
    - Stream Processing: user-guide/streams.md
  - Integrations:
    - Prefect: integrations/prefect.md
    - Kafka: integrations/kafka.md
    - RabbitMQ: integrations/rabbitmq.md
    - SQS: integrations/sqs.md
  - API Reference:
    - Core: api/core.md
    - Pipes: api/pipes.md
    - Streams: api/streams.md
    - Monitoring: api/monitoring.md
  - Examples:
    - Basic Transformation: examples/basic-transformation.md
    - DataFrame Processing: examples/dataframe-processing.md
    - Pipeline Composition: examples/pipeline-composition.md
    - Lambda Composition: examples/lambda-composition.md
    - Prefect Integration: examples/prefect-integration.md
    - Basic Pipeline: examples/basic_pipeline.md
    - Streaming: examples/streaming.md
  - Contributing: contributing.md
  - Changelog: changelog.md
